// 客户端 → 服务端 事件
export enum ClientEvents {
  CREATE_ROOM = 'room:create',
  JOIN_ROOM = 'room:join',
  LEAVE_ROOM = 'room:leave',
  PLAYER_READY = 'room:ready',
  START_GAME = 'room:start',
  GET_CHIPS = 'room:get_chips',
  PLAYER_ACTION = 'game:action',
  SEND_CHAT = 'chat:send',
  VOTE_LEAVE = 'room:vote_leave',
  VOTE_LEAVE_RESPONSE = 'room:vote_leave_response',
  RUN_IT_TWICE_CHOICE = 'game:run_it_twice_choice',
  RUN_IT_TWICE_ROLL_DICE = 'game:run_it_twice_roll_dice',
  DECLINE_REBUY = 'room:decline_rebuy',
}

// 服务端 → 客户端 事件
export enum ServerEvents {
  CONNECTED = 'connection:connected',
  ERROR = 'connection:error',
  ROOM_CREATED = 'room:created',
  ROOM_JOINED = 'room:joined',
  ROOM_LEFT = 'room:left',
  ROOM_UPDATED = 'room:updated',
  PLAYER_JOINED = 'room:player_joined',
  PLAYER_LEFT = 'room:player_left',
  PLAYER_READY_CHANGED = 'room:player_ready_changed',
  GAME_STARTED = 'game:started',
  GAME_ENDED = 'game:ended',
  DEAL_CARDS = 'game:deal_cards',
  COMMUNITY_CARDS = 'game:community_cards',
  PLAYER_TURN = 'game:player_turn',
  ACTION_RESULT = 'game:action_result',
  POT_UPDATED = 'game:pot_updated',
  SHOWDOWN = 'game:showdown',
  HAND_RESULT = 'game:hand_result',
  CHAT_MESSAGE = 'chat:message',
  SYSTEM_MESSAGE = 'system:message',
  CHIPS_RECEIVED = 'system:chips_received',
  ERROR_MESSAGE = 'system:error',
  VOTE_LEAVE_STARTED = 'room:vote_leave_started',
  VOTE_LEAVE_RESPONSE = 'room:vote_leave_response',
  VOTE_LEAVE_ENDED = 'room:vote_leave_ended',
  ROOM_CLOSED = 'room:closed',
  RUN_IT_TWICE_ASK = 'game:run_it_twice_ask',
  RUN_IT_TWICE_CHOICE_RESULT = 'game:run_it_twice_choice_result',
  RUN_IT_TWICE_DICE_RESULT = 'game:run_it_twice_dice_result',
  RUN_IT_TWICE_EXECUTING = 'game:run_it_twice_executing',
  GAME_OVER = 'game:game_over',
}
